#!/usr/bin/env python3
"""Rasterize the non-default Literata reading sizes for the display crate.

Emits display/src/literata_sizes_generated.rs: the 19px and 26px reading
sets (4 styles each) behind the Type Size setting. The default 22px set
stays in literata_generated.rs via tools/generate_literata.py — that file
is deliberately not regenerated here because glyph rasterization differs
across Pillow/freetype builds and regenerating it would churn every
checked-in golden frame that uses the default size.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_sizes_generated.rs"

FONTS = [
    ("REGULAR", "Literata-Regular.ttf"),
    ("ITALIC", "Literata-Italic.ttf"),
    ("BOLD", "Literata-Bold.ttf"),
    ("BOLD_ITALIC", "Literata-BoldItalic.ttf"),
]

# (px, line_height, baseline) — keep ratios close to the 22px set's 30/23.
SIZES = [
    (19, 26, 20),
    (26, 36, 27),
]

# Same coverage as the 22px reading set so a size change never swaps a
# rendered glyph for the '?' fallback.
RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x024F),  # Latin-1, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20CF),  # Currency Symbols
    (0x2100, 0x214F),  # Letterlike Symbols
    (0x2190, 0x21FF),  # Arrows
    (0x25A0, 0x25FF),  # Geometric Shapes
]


def codepoints():
    values = []
    for start, end in RANGES:
        values.extend(range(start, end + 1))
    return sorted(set(values))


def glyph(font, code):
    ch = chr(code)
    bbox = font.getbbox(ch, anchor="ls")
    advance = int(round(font.getlength(ch)))
    if bbox is None:
        return (0, 0, 0, 0, max(advance, 1), [])
    left, top, right, bottom = bbox
    width = max(0, right - left)
    height = max(0, bottom - top)
    if width == 0 or height == 0:
        return (0, 0, left, top, max(advance, 1), [])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(height):
        byte = 0
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= 128:
                byte |= 0x80 >> bits
            bits += 1
            if bits == 8:
                rows.append(byte)
                byte = 0
                bits = 0
        if bits:
            rows.append(byte)
    return (width, height, left, top, max(advance, 1), rows)


def main():
    out = []
    out.append("// Generated by tools/generate_literata_sizes.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric};\n\n")
    cps = codepoints()
    out.append(f"pub const SIZES_COUNT: usize = {len(cps)};\n")
    out.append("pub static SIZES_CODEPOINTS: [u16; SIZES_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for px, line_height, baseline in SIZES:
        for style, filename in FONTS:
            font = ImageFont.truetype(str(FONT_DIR / filename), px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"LITERATA_{px}_{style}"
            out.append(f"pub static {name}_METRICS: [GlyphMetric; SIZES_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"pub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            out.append(f"pub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &SIZES_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
